package com.cnlive.dao;

import com.cnlive.bean.UserBean;
import com.cnlive.bean.UserBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    int countByExample(UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    int deleteByExample(UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    int insert(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    int insertSelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    List<UserBean> selectByExample(UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserBean record, @Param("example") UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri May 31 22:53:31 CST 2019
     */
    int updateByExample(@Param("record") UserBean record, @Param("example") UserBeanExample example);
}